### ISSUE TITLE
(Spike) Investigate adding an image carousel to the Landing page

### ISSUE THREAD

**Issue by WillBAnders** [ufssd/ufssd-website#19]
An image carousel is a standard approach for displaying multiple images (similar to a slideshow). [Bootstrap's carousel](https://getbootstrap.com/docs/4.0/components/carousel/) is a decent example; there are many other variants online.

We want to use an image carousel for displaying SSD photos on the landing page, allowing us to showcase multiple pictures in a compact form. 

## Requirements

 - Determine how feasible it is to add a carousel either via CSS or a standard npm package (recommended).
    - Nice-to-have features would be navigation indicators, auto-transitions, and captions.
 - Create a proof-of-concept for adding an image carousel to the Landing page.
    - If we consider this feasible, then we'll commit to adding this and work on images/polish then.

**Comment by JavierM333** [comment]
Created HTML file that contains the code for the image carousel and added CSS styling to homeModule. It hasn't been implemented into the website, still need to figure out how to do that

**Comment by Brian-Magnuson** [comment]
Making a suggestion here since it seems the last commit made on this was 1 week ago:

This is the carousel I use for my own website. It's a react component you can download from npm. It also has its own demo:
https://www.npmjs.com/package/react-responsive-carousel
http://react-responsive-carousel.js.org/
![image](https://github.com/ufssd/ufssd-website/assets/92892499/91d75a25-b1a0-4e22-b5b7-0b73a06285bf)
